import { z } from 'zod';

/** A CUID2 identifier as generated by Prisma's `@default(cuid(2))`. */
export const idSchema = z.string().min(1, 'Identifier is required');

/** Trimmed, non-empty short text used for names, codes and labels. */
export const shortTextSchema = z.string().trim().min(1).max(160);

/** Optional free-text note. Empty strings are normalised to `undefined`. */
export const noteSchema = z
  .string()
  .trim()
  .max(2000)
  .optional()
  .transform((value) => (value === '' ? undefined : value));

/**
 * Monetary amount. Stored as `Decimal(12, 2)` in Postgres so we never lose
 * precision to floating point, and accepted here as a number with at most two
 * decimal places.
 */
export const moneySchema = z
  .number()
  .nonnegative('Amount cannot be negative')
  .max(99_999_999.99, 'Amount is too large')
  .refine((value) => Number.isFinite(value) && Math.round(value * 100) === value * 100, {
    message: 'Amount may have at most 2 decimal places',
  });

/** A non-negative whole number of units. */
export const quantitySchema = z
  .number()
  .int('Quantity must be a whole number')
  .nonnegative('Quantity cannot be negative')
  .max(10_000_000, 'Quantity is too large');

/** A strictly positive whole number of units, for movements and order lines. */
export const positiveQuantitySchema = quantitySchema.refine((value) => value > 0, {
  message: 'Quantity must be greater than zero',
});

export const sortDirectionSchema = z.enum(['asc', 'desc']);
export type SortDirection = z.infer<typeof sortDirectionSchema>;

/**
 * Cursor-free, offset-based pagination. Offset pagination is the right default
 * here because the dashboard needs jump-to-page and total counts; the API also
 * caps `pageSize` so a client can never ask for an unbounded scan.
 */
export const paginationQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),
  search: z.string().trim().max(160).optional(),
  sortBy: z.string().trim().max(60).optional(),
  sortDir: sortDirectionSchema.default('desc'),
});
export type PaginationQuery = z.infer<typeof paginationQuerySchema>;

/** Shape of the `meta` block returned alongside every paginated list. */
export interface PaginationMeta {
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
}

/** Envelope returned by every list endpoint. */
export interface Paginated<TItem> {
  items: TItem[];
  meta: PaginationMeta;
}

/**
 * Builds a Zod schema for a paginated envelope around an item schema. Used by
 * the web client to validate list responses at the network boundary.
 *
 * @param itemSchema - Schema describing one row of the list.
 * @returns A schema for `{ items, meta }`.
 */
export function paginatedSchema<TSchema extends z.ZodType>(itemSchema: TSchema) {
  return z.object({
    items: z.array(itemSchema),
    meta: z.object({
      page: z.number(),
      pageSize: z.number(),
      totalItems: z.number(),
      totalPages: z.number(),
      hasNextPage: z.boolean(),
      hasPreviousPage: z.boolean(),
    }),
  });
}

/**
 * Computes the pagination envelope for a page of results.
 *
 * @param page - 1-based page number that was requested.
 * @param pageSize - Number of rows per page.
 * @param totalItems - Total rows matching the filter, ignoring pagination.
 * @returns The `meta` block describing the page.
 */
export function buildPaginationMeta(
  page: number,
  pageSize: number,
  totalItems: number,
): PaginationMeta {
  const totalPages = totalItems === 0 ? 0 : Math.ceil(totalItems / pageSize);
  return {
    page,
    pageSize,
    totalItems,
    totalPages,
    hasNextPage: page < totalPages,
    hasPreviousPage: page > 1 && totalItems > 0,
  };
}

/**
 * Consistent error body returned by the API for every failure, so integrators
 * only ever have to parse one shape.
 */
export interface ApiErrorBody {
  statusCode: number;
  error: string;
  message: string;
  /** Field-level validation issues, present only on 422 responses. */
  details?: Array<{ path: string; message: string }>;
  path: string;
  timestamp: string;
  requestId: string;
}
