import 'dotenv/config';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { Client } from 'pg';

/**
 * Exports the seeded demo data as a portable SQL file.
 *
 * Written by hand rather than shelling out to `pg_dump` so the deliverable does
 * not depend on the reviewer having Postgres client tools installed, and so the
 * output is plain `INSERT` statements that can be read, diffed and applied
 * anywhere — including a database that is not Postgres 16.
 *
 * Tables are emitted in dependency order, and the file is wrapped in a single
 * transaction so a partial apply cannot leave a half-populated database.
 */

/** Tables in insert order — parents before children. */
const TABLES = [
  'users',
  'organizations',
  'memberships',
  'warehouses',
  'warehouse_members',
  'categories',
  'suppliers',
  'products',
  'stock_levels',
  'stock_movements',
  'stock_transfers',
  'stock_transfer_items',
  'purchase_orders',
  'purchase_order_items',
  'sales_orders',
  'sales_order_items',
  'document_counters',
  'bulk_jobs',
  'audit_logs',
] as const;

/** Renders one value as a SQL literal. */
function toSqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (value instanceof Date) return `'${value.toISOString()}'`;

  if (typeof value === 'object') {
    // Json columns; single quotes doubled for SQL escaping.
    return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  }

  return `'${String(value).replace(/'/g, "''")}'`;
}

async function main(): Promise<void> {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error('DATABASE_URL is not set');
  }

  const client = new Client({ connectionString });
  await client.connect();

  const lines: string[] = [
    '-- ---------------------------------------------------------------------------',
    '-- Warehouse & Inventory Management System — sample data',
    '--',
    '-- Generated by `pnpm db:dump`. Apply on top of a database that already has the',
    '-- schema (run `pnpm db:deploy` first):',
    '--',
    '--   psql "$DATABASE_URL" -f sample-data.sql',
    '--',
    '-- Every account uses the password: Praella@2026',
    '-- ---------------------------------------------------------------------------',
    '',
    'BEGIN;',
    '',
    '-- Clear any existing rows so the file is idempotent.',
    `TRUNCATE TABLE ${[...TABLES].reverse().join(', ')} RESTART IDENTITY CASCADE;`,
    '',
  ];

  let totalRows = 0;

  for (const table of TABLES) {
    const { rows, fields } = await client.query(
      `SELECT * FROM "${table}" ORDER BY 1`,
    );

    lines.push(`-- ${table} (${rows.length} row${rows.length === 1 ? '' : 's'})`);

    if (rows.length === 0) {
      lines.push('');
      continue;
    }

    const columns = fields.map((field) => `"${field.name}"`).join(', ');

    // Batched so a large ledger does not become 400 separate statements.
    const CHUNK = 50;
    for (let offset = 0; offset < rows.length; offset += CHUNK) {
      const chunk = rows.slice(offset, offset + CHUNK);
      const values = chunk
        .map(
          (row) =>
            `  (${fields.map((field) => toSqlLiteral(row[field.name])).join(', ')})`,
        )
        .join(',\n');

      lines.push(`INSERT INTO "${table}" (${columns}) VALUES`, `${values};`, '');
    }

    totalRows += rows.length;
  }

  lines.push('COMMIT;', '');

  await client.end();

  const outputPath = path.join(process.cwd(), '..', '..', 'sample-data.sql');
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, lines.join('\n'), 'utf8');

  console.log(
    `✔ Wrote ${totalRows} rows across ${TABLES.length} tables to ${path.resolve(outputPath)}`,
  );
}

main().catch((error: unknown) => {
  console.error('Dump failed:', error);
  process.exitCode = 1;
});
